---
title: "Unit 11 Sunspot"
author: "Bivin"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# Need to update in tswge (turn plot = FALSE in gen.arma.wge)
gen.sigplusnoise.wge = function (n, b0 = 0, b1 = 0, coef = c(0, 0), freq = c(0, 0), 
    psi = c(0, 0), phi = 0, vara = 1, plot = "TRUE", sn = 0) 
{
    if (sn > 0) {
        set.seed(sn)
    }
    std = sqrt(vara)
    t = 1:n
    zt = gen.arma.wge(n = n, phi = phi, theta = 0, vara = vara, 
        sn = sn, plot = FALSE) #update plot = FALSE
    x = b0 + b1 * t + coef[1] * cos(2 * pi * freq[1] * t + psi[1]) + 
        coef[2] * cos(2 * pi * freq[2] * t + psi[2]) + zt
    numrows <- 1
    numcols <- 1
    fig.width <- 5.5
    fig.height <- 4.5
    cex.labs <- c(0.8, 0.7, 0.9)
    par(mfrow = c(numrows, numcols), mar = c(3.8, 2.5, 1, 1))
    if (plot == "TRUE") {
        plot(t, x, type = "l")
    }
    return(x)
}

```

# Cos Signal + Noise
```{r}
#SS = read.csv(file.choose(),header = TRUE)

data(patemp)

plotts.wge(patemp)
parzen.wge(patemp)

#modeling signal plus noise with correlated noise (AR(1))
fore.patemp.spn = fore.sigplusnoise.wge(patemp,freq = .083, n.ahead = 24, limits = FALSE, linear = FALSE, lastn = TRUE, max.p = 10)
fore.patemp.spn
ASE.spn = mean((patemp[(length(patemp)-23): length(patemp)]-fore.patemp.spn$f)^2)
ASE.spn


#Compare Spectral Densities
sims = 10
SpecDen = parzen.wge(patemp, plot = "FALSE")
plot(SpecDen$freq,SpecDen$pzgram, type = "l", lwd = 6)

for( i in 1: sims)
{
   SpecDen2 = parzen.wge(gen.sigplusnoise.wge(length(patemp), b0 = fore.patemp.spn$b[1], freq = c(.083,0),coef = c(fore.patemp.spn$b[2],0), phi = fore.patemp.spn$phi.z, psi = c(fore.patemp.spn$b[3],0), plot = FALSE), plot = FALSE)
   lines(SpecDen2$freq,SpecDen2$pzgram, lwd = 2, col = "red")
}


#Compare ACFs
sims = 10
ACF = acf(patemp, plot = "FALSE")
plot(ACF$lag ,ACF$acf , type = "l", lwd = 6)

for( i in 1: sims)
{
   ACF2 = acf(gen.aruma.wge(length(patemp), s = 12, plot =    "FALSE"), plot = "FALSE")
   lines(ACF2$lag ,ACF2$acf, lwd = 2, col = "red")
}

#Compare Generated Realizations 


S10AR3gen = gen.aruma.wge(319,s = 10,phi = AR3$phi, vara = AR3$avar)

plotts.sample.wge(S10AR3gen)

```


# Non Stationary
## (1-B^12)ARMA
```{r}
plotts.sample.wge(patemp)
est.ar.wge(patemp,p = 15) #overfit for seasonality
factor.wge(c(rep(0,12),1)) # for reference
PA_12 = artrans.wge(patemp,phi.tr = c(rep(0,11),1))
aic5.wge(PA_12, p = 0:5, q = 0:2)
aic5.wge(PA_12, type = "bic", p = 0:5, q = 0:2)
AR1 = est.arma.wge(PA_12,p = 1,q = 0)
PA_12_AR1 = artrans.wge(PA_12,AR1$phi)
ljung.wge(PA_12_AR1)
ljung.wge(PA_12_AR1, K = 48)
f = fore.arima.wge(patemp,s = 12,phi = AR1$phi,n.ahead = 24,limits = FALSE,lastn = TRUE)

ASE = mean((patemp[(length(patemp)-23):length(patemp)] - f$f)^2)

ASE


#Rolling Window ASE
roll.win.rmse.wge(patemp,s = 12, phi = AR1$phi, horizon = 24)


#Compare Spectral Densities
sims = 5
SpecDen = parzen.wge(patemp, plot = "FALSE")
plot(SpecDen$freq,SpecDen$pzgram, type = "l", lwd = 6)

for( i in 1: sims)
{
   SpecDen2 = parzen.wge(gen.aruma.wge(289,s = 12, phi = AR1$phi, theta = AR1$theta, plot = "FALSE"), plot = "FALSE")
   lines(SpecDen2$freq,SpecDen2$pzgram, lwd = 2, col = "red")
}


#Compare ACFs
sims = 5
ACF = acf(patemp, plot = "FALSE")
plot(ACF$lag ,ACF$acf , type = "l", lwd = 6)

for( i in 1: sims)
{
   ACF2 = acf(gen.aruma.wge(289, s = 12, phi = AR1$phi, theta = AR1$theta, plot =    "FALSE"), plot = "FALSE")
   lines(ACF2$lag ,ACF2$acf, lwd = 2, col = "red")
}

```
